# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode version (Optional, but good practice if you need a specific version)
      run: |
        sudo xcode-select -switch /Applications/Xcode_15.3.app/Contents/Developer # Example for Xcode 15.3
        # Find available Xcode versions by running 'ls /Applications | grep Xcode' locally or in a previous workflow run
        # For a specific version, check GitHub Actions documentation for available images
        xcodebuild -version # Verify selected version
        
    - name: Build Xcode Project
      run: |
        xcodebuild clean build \
          -scheme "GenAIKathaApp" \
          -project "GenAIKathaApp.xcodeproj" \
          -destination "platform=iOS Simulator,name=iPhone 15,OS=latest" \
          -configuration Release \
          CODE_SIGNING_ALLOWED=NO CODE_SIGN_IDENTITY="" \
          -derivedDataPath ./build-output # Using a distinct path for derived data
      working-directory: ./GenAIKathaApp/
      
    - name: Run Xcode Tests
      run: |
        xcodebuild test \
          -scheme "GenAIKathaApp" \
          -project "GenAIKathaApp.xcodeproj" \
          -destination "platform=iOS Simulator,name=iPhone 15,OS=latest" \
          CODE_SIGNING_ALLOWED=NO CODE_SIGN_IDENTITY="" \
          -derivedDataPath ./build-output # Using the same derived data path as build
      working-directory: ./GenAIKathaApp/

